# This namespace enables:

# ✔ Dedicated environment for Velero
# ✔ Secure privileged access for cluster backups
# ✔ Isolation from application workloads
# ✔ Clear infrastructure classification
# ✔ Foundation for disaster recovery system (backup + restore of Kubernetes cluster)


# This file creates a secure, isolated, and resource-limited namespace for Velero to safely perform backups and restores.

apiVersion: v1  # Core Kubernetes API version for basic resources
kind: Namespace  # Creates a separate logical environment in the cluster
metadata:
  name: velero  # Namespace where Velero and related components will run
  labels:
    pod-security.kubernetes.io/enforce: privileged  # Enforces privileged security level (required for Velero to access volumes like EBS)
    name: velero  # Label to identify the namespace
    tier: infrastructure  # Marks this namespace as infra-level (not app-level)
    purpose: disaster-recovery  # Indicates this namespace is used for backups and recovery
