apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rohandeb2/sspringboot-bankapp
    targetRevision: HEAD
    path: k8s-manifests/argocd-infra/vpa
    directory:
      recurse: false
      # Apply in filename order: 1_, 2_, 3_, 4_, 5_
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    # cert-manager manages caBundle — ignore ArgoCD drift on this field
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vpa-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
