
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-webhook-tls
  namespace: kube-system
spec:
  secretName: vpa-tls-certs
  duration: 8760h
  renewBefore: 720h
  commonName: vpa-webhook.kube-system.svc
  dnsNames:
    - vpa-webhook.kube-system.svc
    - vpa-webhook.kube-system.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: vpa-ca-issuer
    kind: Issuer
    group: cert-manager.io
  # usages required for a TLS server cert
  usages:
    - server auth
    - digital signature
    - key encipherment
