{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "banking.fullname" . }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.istio.host }}"
  gateways:
  - {{ include "banking.fullname" . }}-gateway
  http:
  - name: "banking-api-routes"
    route:
    - destination:
        host: {{ include "banking.fullname" . }}-active
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
    timeout: 10s
    corsPolicy:
      allowOrigins:
        - exact: "https://rohandevops.co.in"
      allowMethods:
        - POST
        - GET
      allowHeaders:
        - content-type
{{- end }}
