{{- if .Values.serviceAccount.create -}} # Create ServiceAccount only if enabled in values.yaml
apiVersion: v1 # Kubernetes core API version
kind: ServiceAccount # Defines a ServiceAccount resource for pod identity
metadata:
  name: {{ include "banking.fullname" . }} # Dynamically generates full name using Helm helper template
  namespace: {{ .Values.namespace }} # Deploys ServiceAccount into the specified namespace from values.yaml
  labels:
    {{- include "banking.labels" . | nindent 4 }} # Injects common labels using Helm helper template with proper indentation
  annotations: # Annotations provide metadata for AWS IAM Roles for Service Accounts (IRSA)
    {{- with .Values.serviceAccount.annotations }} # If annotations are provided in values.yaml, include them
    {{- toYaml . | nindent 4 }} # Convert annotations map to YAML and indent correctly
    {{- end }} # End conditional block for annotations
    eks.amazonaws.com/audience: "sts.amazonaws.com" # Defines audience for the service account token (used by AWS STS)
    eks.amazonaws.com/token-expiration: "86400" # Sets token validity to 86400 seconds (24 hours)
automountServiceAccountToken: true # Automatically mounts service account token into pods for authentication
{{- end -}} # End conditional creation block

# 👉 ServiceAccount = WHO you are
# 👉 RBAC / IAM Role = WHAT you can do

# Why do we create a ServiceAccount?

  # By default, every pod gets a default identity.
  # But in real-world systems, we want:

  # ✅ 1. Fine-grained permissions (security)
  # Instead of giving all pods full access:
  # You create a ServiceAccount
  # Attach RBAC roles to it

  # 👉 Example:

  # Pod A → can read secrets
  # Pod B → can only read configmaps

#   When the banking app needs to talk to the Kubernetes API (to find other pods) or to AWS 
#   (to get database secrets), it presents this ServiceAccount as its ID card.

# The automountServiceAccountToken: true line ensures Kubernetes drops a security
#  token into the pod at /var/run/secrets/kubernetes.io/serviceaccount/token

# When the pod starts, EKS sees this annotation and calls AWS STS (Security Token Service).

# Your Java app gets "Temporary Security Credentials." It can now upload logs to S3 or 
# read secrets from AWS Secrets Manager without you ever having to hardcode an AWS Access 
# Key or Secret Key