apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: banking-guardrails

spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: check-resource-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - banking-prod
      validate:
        message: Resource limits are required.
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
                    memory: "?*"
    - name: disallow-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - monitoring
                - velero
                - kyverno
                - kube-system
                - argocd
                - jenkins
                - istio-system
      validate:
        message: Running containers as root is not allowed.
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true