name: "Terraform 02 - Production Deployment"

on:
  push:
    branches: [main]
    paths: 
      - 'terraform/modules/**'
      - 'terraform/prod/**'
  pull_request:
    branches: [main]
    paths: 
      - 'terraform/modules/**'
      - 'terraform/prod/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate-and-deploy:
    name: "Core Infrastructure Engine"
    runs-on: ubuntu-latest
    env:
      TF_PROD: "./terraform/prod"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          aws-region: us-east-1

      - name: Run Checkov (Recursive Scan of Prod & Modules)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform   
          framework: terraform     
          quiet: true               
          soft_fail: true          

      - name: Setup & Run TFLint
        uses: terraform-linters/setup-tflint@v4     

      - name: Recursive Linting
        run: |
          tflint --init
          tflint --recursive --f compact

      - name: Terraform Init (Prod)
        working-directory: ${{ env.TF_PROD }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_PROD }}
        run: terraform plan -no-color -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'  
        working-directory: ${{ env.TF_PROD }}
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"