apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: banking-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: banking-repo-creds   
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository # Label to identify this secret as a repository credential for Argo CD
      data: 
        type: git
        url: https://github.com/rohandeb2/sspringboot-bankapp.git
        enableLfs: "true" # Enable Git LFS support if your repo uses Git Large File Storage (LFS) for large files
        skipVerification: "false" # Skip SSL verification (use with caution)

  data:
  - secretKey: username
    remoteRef:
      key: banking-github-creds
      property: git-username

  - secretKey: password
    remoteRef:
      key: banking-github-creds
      property: git-password