apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-stack-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # 1. Main Application
          - appName: banking-platform
            path: k8s-manifests/banking-platform # Corrected Path
            namespace: banking-prod
            env: prod
          
          # 2. Istio Networking (Fixing your deployment issue)
          - appName: istio-base
            path: k8s-manifests/argocd-infra/networking
            namespace: istio-system
            env: infra-istio

          # 3. SonarQube (Fixing your deployment issue)
          - appName: sonarqube
            path: k8s-manifests/devsecops # Path where sonarqube-stack.yaml lives
            namespace: devsecops
            env: security

  template:
    metadata:
      name: '{{env}}-{{appName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp'
        targetRevision: HEAD
        path: '{{path}}' # Dynamic path based on the list above
        # If it's a Helm chart, it uses these. If plain YAML, it ignores them.
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true