apiVersion: argoproj.io/v1alpha1 # Argo CD API version
kind: ApplicationSet # Generates multiple Argo CD Applications dynamically
metadata:
  name: banking-app-set # Name of the ApplicationSet
  namespace: argocd # Must be in Argo CD namespace
spec:
  #It generates one Argo CD Application per element in the list
  generators: # Defines how apps are created dynamically 
    - list: #  Generates apps based on a static list of cluster/namespace combinations
        elements: #Each element = one app instance
          - cluster: in-cluster # Target cluster name
            url: https://kubernetes.default.svc # Kubernetes API server
            namespace: banking-prod # Target namespace for deployment
            valuesFile: values-prod.yaml # Environment-specific Helm values file
            env: prod # Environment identifier used in naming

  # For each generated element, create an Application using this template.
  template:
    metadata:
      name: '{{env}}-banking-platform' # Dynamically generates app name (e.g., prod-banking-platform)
    spec:
      project: banking-core-project # Uses AppProject for governance and security rules and must match the name of the AppProject defined in app-project.yaml
      
      source:
        repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp' # Git repo containing Helm chart
        targetRevision: HEAD # Always deploy latest commit (not ideal for strict prod, but common)
        path: banking-platform # Path inside repo where Helm chart exists
        helm:
          valueFiles:
            - values.yaml # Base configuration
            - '{{valuesFile}}' # Environment-specific override (values-prod.yaml)
      
      destination:
        server: '{{url}}' # Target cluster (dynamic)
        namespace: '{{namespace}}' # Target namespace (dynamic)
      
      syncPolicy:
        automated:
          prune: true # Removes resources not present in Git (prevents drift)
          selfHeal: true # Automatically fixes drift if someone changes cluster manually
        syncOptions:
          - CreateNamespace=true # Automatically creates namespace if not exists
          - Validate=true # Validates against AppProject rules before deployment