# it will Manage all  Argo CD infrastructure (AppProject, ApplicationSet, etc.) in a single place using GitOps
# This is a parent application managing everything like under argocd-infra folder argocd will scan all yaml file and apply all resource automatically

apiVersion: argoproj.io/v1alpha1 # Argo CD API version
kind: Application # Defines a single Argo CD application
metadata:
  name: root-banking-stack # Root (parent) application managing infra
  namespace: argocd # Must exist in Argo CD namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures child resources/apps are deleted safely before this app is removed
spec:
  project: default # Uses default project because it manages AppProject and other infra (higher-level resources)
  
  source:
    repoURL: 'https://github.com/rohan/Springboot-BankApp.git' # Git repo containing infra configs
    targetRevision: HEAD # Tracks latest commit (not ideal for strict prod, but common in setups)
    path: argocd-infra # Folder containing all Argo CD infra YAMLs (AppProject, ApplicationSet, etc.)
    directory:
      recurse: true # Reads all YAML files recursively inside this folder

  destination:
    server: 'https://kubernetes.default.svc' # Deploys to in-cluster Kubernetes
    namespace: argocd # All infra resources are created in argocd namespace

  syncPolicy:
    automated:
      prune: true # Deletes resources that are removed from Git (keeps cluster clean)
      selfHeal: true # Reverts any manual changes in cluster back to Git state
    syncOptions:
      - CreateNamespace=true # Creates namespace if it doesn't exist
      - ApplyOutOfSyncOnly=true # Optimizes sync by applying only changed resources