apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-app-set
  namespace: argocd
spec:
  # 1. Generators: Define where this app should be deployed
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            namespace: banking-prod
            valuesFile: values-prod.yaml
            env: prod
  
  # 2. Template: This is the "Blueprint" for each Application
  template:
    metadata:
      name: '{{env}}-banking-platform' # Results in "prod-banking-platform"
    spec:
      # Use the AppProject we created in Step 1
      project: banking-core-project
      
      source:
        repoURL: 'https://github.com/rohan/Springboot-BankApp.git'
        targetRevision: HEAD
        path: banking-platform # Path to your Helm Chart
        helm:
          # --- 12 LPA LOGIC: DYNAMIC OVERRIDES ---
          # This pulls 'values-prod.yaml' for the Prod environment automatically
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'
      
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      
      # 3. Sync Policy: Automated self-healing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          # Ensures that the AppProject restrictions are checked before syncing
          - Validate=true