apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-banking-stack
  namespace: argocd
  # Finalizers ensure that if you delete this Master App, 
  # it cleans up all child apps safely.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # 1. Project: Uses the 'default' project because this app MANAGES 
  # the 'banking-core-project'.
  project: default
  
  source:
    repoURL: 'https://github.com/rohan/Springboot-BankApp.git'
    targetRevision: HEAD
    path: argocd-infra # This points to the folder containing all infra YAMLs
    directory:
      recurse: true # Tells Argo to look at every file in the folder

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd # Infra management stays in the argocd namespace

  # 2. Sync Policy: High-level automation
  syncPolicy:
    automated:
      prune: true     # Automatically deletes old infra configs
      selfHeal: true  # Prevents manual 'kubectl' edits to your Argo settings
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true # Optimization: Only sync files that changed