apiVersion: v1
kind: ConfigMap

metadata:
  name: tempo-datasource
  namespace: monitoring

  labels:
    grafana_datasource: "1"

data:
  tempo-ds.yaml: |-
    apiVersion: 1

    datasources:
      - name: Tempo
        type: tempo
        uid: tempo-prod-01

        url: http://tempo-stack.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false

        jsonData:
          lokiSearch:
            datasourceUid: loki

          serviceMap:
            datasourceUid: prometheus

          nodeGraph:
            enabled: true

          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
            tags:
              - job
              - instance
              - pod
              - namespace
            filterByTraceId: true
            filterBySpanId: false