apiVersion: v1
kind: ServiceAccount

metadata:
  name: tempo-sa
  namespace: monitoring

  labels:
    app.kubernetes.io/name: tempo-stack
    app.kubernetes.io/instance: tempo-stack
    app.kubernetes.io/component: distributed-tracing
    env: production

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::959589242185:role/tempo-s3-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"