apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kiali-server
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://kiali.github.io/helm-charts
    chart: kiali-server
    targetRevision: 1.89.0

    helm:
      values: |
        auth:
          strategy: anonymous

        deployment:
          sidecar_container_config:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

        external_services:
          prometheus:
            url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090

          grafana:
            enabled: true
            url: http://grafana.monitoring.svc.cluster.local

          tracing:
            enabled: true
            url: http://tempo-stack.monitoring.svc.cluster.local:3100

        server:
          observability:
            tracing:
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true