apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 11.4.0
    helm:
      values: |
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: us-east-1
                s3ForcePathStyle: "true"
                s3Url: http://minio.velero.svc.cluster.local:9000
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-east-1
        credentials:
          useSecret: true
          existingSecret: velero-minio-secret
        serviceAccount:
          server:
            create: true
            name: velero-server
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            volumeMounts:
              - mountPath: /target
                name: plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /spec/preserveUnknownFields
        - /spec/versions
        - /status
    - group: velero.io
      kind: BackupStorageLocation
      jsonPointers:
        - /spec/accessMode
        - /status
