apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: banking-prod-daily-backup
  namespace: velero
  labels:
    component: disaster-recovery
    env: production
    backup-group: fintech-core
spec:
  schedule: "0 */6 * * *"
  template:
    includedNamespaces:
      - banking-prod
    ttl: 720h0m0s
    snapshotVolumes: false
    storageLocation: default
