apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: log-anomaly-alerts
  namespace: monitoring
spec:
  groups:
  - name: ai-log-alerts
    rules:
    - alert: HighLogAnomalyScore
      expr: increase(kube_pod_container_status_restarts_total{namespace="banking-prod"}[5m]) > 3
      for: 2m
      annotations:
        summary: "Anomaly detected in banking pods"
