apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sonarqube
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://sonarsource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 10.0.0

    helm:
      values: |
        postgresql:
          enabled: true
          postgresqlPassword: "rohan-secure-pass"

          persistence:
            size: 20Gi

        persistence:
          enabled: true
          size: 10Gi

        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

        ingress:
          enabled: true
          hosts:
            - name: sonarqube.rohandevops.co.in

  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true