apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: banking-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: banking-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://github.com/rohandeb2/sspringboot-bankapp.git"
        enableLfs: "true"
        skipVerification: "false"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: banking-github-creds
        property: git_username
    - secretKey: password
      remoteRef:
        key: banking-github-creds
        property: git_password