apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-stack-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: banking-platform
            path: banking-app
            namespace: banking-prod
            env: prod

          - appName: istio-base
            path: service-mesh/networking
            namespace: istio-system
            env: infra-istio

          - appName: sonarqube
            path: security-scanning/devsecops
            namespace: devsecops
            env: security

  template:
    metadata:
      name: '{{env}}-{{appName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp'
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true