apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: banking-core-project
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  description: Spring Boot banking application

  sourceRepos:
    - https://github.com/rohandeb2/sspringboot-bankapp.git

  destinations:
    - namespace: banking-prod
      server: https://kubernetes.default.svc
      name: in-cluster

  # allow namespace creation
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: apps
      kind: StatefulSet

    - group: argoproj.io
      kind: Rollout

    - group: argoproj.io
      kind: AnalysisRun

    - group: networking.k8s.io
      kind: Ingress

    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: ""
      kind: Service

    - group: ""
      kind: ConfigMap

    - group: ""
      kind: Secret

    - group: autoscaling
      kind: HorizontalPodAutoscaler

  roles:
    - name: read-only
      description: QA access

      policies:
        - p, proj:banking-core-project:read-only, applications, get, banking-core-project/*, allow

    - name: srv-admin
      description: DevOps admin role

      policies:
        - p, proj:banking-core-project:srv-admin, applications, *, banking-core-project/*, allow

  orphanedResources:
    warn: true