# This ApplicationSet dynamically generates multiple ArgoCD applications for application, infrastructure, 
# and security stacks, enabling fully automated GitOps-based multi-environment deployments.

# This single file gives you:

# ✔ 3 production systems deployed automatically
# ✔ Fully Git-driven infrastructure
# ✔ Zero manual ArgoCD app creation
# ✔ Scalable platform design
# ✔ Clean separation of workloads

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-stack-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: banking-platform
            path: banking-app
            namespace: banking-prod
            env: prod
          - appName: istio-base
            path: service-mesh/networking
            namespace: istio-system
            env: infra-istio
          - appName: sonarqube
            path: security-scanning/devsecops
            namespace: devsecops
            env: security
  template:
    metadata:
      name: '{{env}}-{{appName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp'
        targetRevision: HEAD
        path: '{{path}}'
        # NO helm: block here — these are plain YAML manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true