apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-github-oauth
  namespace: jenkins
spec:
  refreshInterval: 1h # Automatically syncs if you rotate the secret in AWS
  secretStoreRef:
    name: aws-secretsmanager # Matches your SecretStore in argocd-infra
    kind: ClusterSecretStore
  target:
    name: github-oauth-secret # This is the name of the K8s secret it will create
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: jenkins-secret
        property: client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: jenkins-secret
        property: client-secret # 
    - secretKey: SONAR_QUBE_TOKEN
      remoteRef:
        key: jenkins-secret # Secret name in AWS Secrets Manager
        property: sonar-token
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: jenkins-secret # Secret name in AWS Secrets Manager
        property: gemini-api-key