apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.0
    helm:
      values: |
        global:
          meshID: mesh1
          multiCluster:
            clusterName: banking-prod-eks
        pilot:
          autoscaleEnabled: true
          autoscaleMin: 2
          autoscaleMax: 5
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 4Gi
        meshConfig:
          accessLogFile: /dev/stdout
          enableTracing: true
          defaultConfig:
            tracing:
              sampling: 100
              max_path_tag_length: 256
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].failurePolicy
