#This file tells Prometheus how to find and scrape metrics from your application

{{- if .Values.serviceMonitor.enabled -}} # Create ServiceMonitor only if enabled in values.yaml
apiVersion: monitoring.coreos.com/v1 # API for Prometheus Operator CRDs
kind: ServiceMonitor # Defines how Prometheus should scrape metrics from services
metadata:
  name: {{ include "banking.fullname" . }} # Name of the ServiceMonitor
  namespace: {{ .Values.namespace }} # Namespace where ServiceMonitor is created
  labels:
    {{- include "banking.labels" . | nindent 4 }} # Common labels for identification
    release: kube-prometheus-stack # Label to associate with Prometheus release (if using kube-prometheus-stack)
spec:
  selector:
    matchLabels:
      app: {{ include "banking.fullname" . }} # Targets Services with this label (not pods directly)
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }} # Tells Prometheus to look for services in this namespace
  endpoints:
    - port: http # Uses the named port from the Service definition
      path: {{ .Values.serviceMonitor.path | default "/actuator/prometheus" | quote }} # Metrics endpoint exposed by application
      interval: {{ .Values.serviceMonitor.interval | default "30s" | quote }} # How frequently Prometheus scrapes metrics
      scrapeTimeout: 10s # Max time Prometheus waits for a response before failing
      relabelings:
        - targetLabel: application # Adds/overwrites label in Prometheus metrics
          replacement: banking-core # Sets a clean, consistent app name for dashboards
{{- end }} # End conditional block