apiVersion: v1  # Core Kubernetes API for basic resources like ConfigMap
kind: ConfigMap  # Stores non-sensitive configuration data as key-value pairs
metadata:
  name: {{ include "banking.fullname" . }}-config  # Dynamic name using Helm helper; ensures uniqueness per release
  namespace: {{ .Values.namespace }}  # Deploys ConfigMap into the target namespace
  labels:
    {{- include "banking.labels" . | nindent 4 }}  # Reusable labels for identification, filtering, and consistency
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | default "prod" | quote }}  # It tells your app: “Which environment am I running in?”
  LOG_LEVEL: {{ .Values.config.logLevel | default "INFO" | quote }}  # Controls logging verbosity Examples: DEBUG → very detailed logs ---> INFO → normal logs --> ERROR → only errors
                                                                      # quote ->This converts value into a string with quotes
  DB_HOST: {{ .Values.config.dbHost | quote }}  # Database endpoint (e.g., AWS RDS hostname)
  DB_PORT: {{ .Values.config.dbPort | default "3306" | quote }}  # Database port; defaults to MySQL (3306)
  DB_NAME: {{ .Values.config.dbName | quote }}  # Name of the database your app connects to

  ENABLE_TRANSACTION_LIMITS: "true"  # Feature flag to enable transaction limits in application logic
  MAX_DAILY_TRANSFER: "50000"  # Business rule: maximum allowed transfer per day