apiVersion: external-secrets.io/v1beta1  # API for External Secrets Operator (ESO)
kind: ExternalSecret  # This resource syncs secrets from external providers (like AWS)
metadata:
  name: {{ include "banking.fullname" . }}-db-secrets  # Name of ExternalSecret resource
  namespace: {{ .Values.namespace }}  # Namespace where secret will be created
  labels:
    {{- include "banking.labels" . | nindent 4 }}  # Standard labels for identification
spec:
  refreshInterval: "1h"  # ESO checks AWS every 1 hour for updates (supports secret rotation)

  secretStoreRef:
    name: aws-secrets-manager  # Reference to ClusterSecretStore that defines how to connect to AWS Secrets Manager
    kind: ClusterSecretStore  # This means the secret store is cluster-wide and can be used across namespaces

  target:
    name: {{ include "banking.fullname" . }}-db-secrets  # Kubernetes Secret that will be created that means k8s will create a secret with this name in the same namespace
    creationPolicy: Owner  # ESO owns and manages lifecycle of this secret

  data:
  # Take password from AWS and store it in Kubernetes Secret under key DB_PASSWORD
    - secretKey: DB_PASSWORD  # Key inside Kubernetes Secret
      remoteRef:
        key: {{ .Values.secrets.awsSecretName | quote }}  # Name of secret in AWS Secrets Manager Go to AWS Secrets Manager and find this secret
        property: db_password  # Fetch "password" field from AWS secret JSON

    - secretKey: DB_USERNAME  # Another key inside Kubernetes Secret
      remoteRef:
        key: {{ .Values.secrets.awsSecretName | quote }}  # Same AWS secret
        property: db_username  # Fetch "username" field from AWS secret JSON