{{- if .Values.hpa.enabled -}} # Create HPA only if enabled in values.yaml
apiVersion: autoscaling/v2 # Uses advanced HPA API (supports multiple metrics)
kind: HorizontalPodAutoscaler # Automatically scales pods based on metrics
metadata:
  name: {{ include "banking.fullname" . }} # HPA name matches application
  namespace: {{ .Values.namespace }} # Deploys HPA in the same namespace
  labels:
    {{- include "banking.labels" . | nindent 4 }} # Applies common labels
spec:
  scaleTargetRef:  # Specifies which Deployment to scale
    apiVersion: argoproj.io/v1alpha1 # Target resource API version
    kind: Rollout # Resource type to scale (Rollout in this case)
    name: {{ include "banking.fullname" . }} # Name of the Rollout to scale
  minReplicas: {{ .Values.hpa.minReplicas | default 3 }} # Minimum number of pods always running
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }} # Maximum number of pods allowed during scaling
  metrics:
    - type: Resource # Uses built-in resource metrics
      resource:
        name: cpu # CPU-based scaling
        target:
          type: Utilization # Based on % of requested CPU
          averageUtilization: {{ .Values.hpa.targetCPU | default 70 }} # Scale when avg CPU > 70%
{{- end }} # End conditional block