apiVersion: policy/v1 # API version for PodDisruptionBudget
kind: PodDisruptionBudget # Ensures minimum pod availability during voluntary disruptions
metadata:
  name: {{ include "banking.fullname" . }} # Name of the PDB (same as app)
  namespace: {{ .Values.namespace }} # Namespace where PDB is applied
  labels:
    {{- include "banking.labels" . | nindent 4 }} # Common labels for identification
spec:
  minAvailable: 2 # At least 2 pods must always remain running
  selector:
    matchLabels:
      app: {{ include "banking.fullname" . }} # Applies PDB to pods with this label