apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "banking.fullname" . }}-db-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
spec:
  # 1. How often to check AWS for password changes (12 LPA logic: Rotation)
  refreshInterval: "1h"
  
  # 2. Which SecretStore to use (Points to your AWS IAM Role)
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # 3. What to fetch from AWS
  target:
    name: {{ include "banking.fullname" . }}-db-pass
    creationPolicy: Owner
  
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsSecretName | quote }}
        property: password # Fetches the 'password' key from the JSON in AWS
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secrets.awsSecretName | quote }}
        property: username