apiVersion: v1
kind: Namespace
metadata:
  # This dynamically fetches the namespace name from your values file
  name: {{ .Values.namespace | default "banking-default" }}
  labels:
    # --- 12 LPA LOGIC: SECURITY ENFORCEMENT ---
    # This prevents anyone from running "privileged" or "root" containers in this namespace
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    
    # --- IDENTIFICATION & COST TRACKING ---
    env: {{ .Values.environment | default "prod" }}
    team: {{ .Values.team | default "fintech" }}
    managed-by: {{ .Release.Service }} # Usually "Helm"
    
    # --- OBSERVABILITY ---
    # Tells Prometheus/Istio to automatically monitor this namespace
    istio-injection: enabled
    monitoring: prometheus
  annotations:
    # Audit trail for the DevOps team
    description: "Production environment for Banking Microservices"
    owner: {{ .Values.ownerEmail | default "rohan@rohandevops.co.in" }}
    last-updated: {{ now | date "2006-01-02" | quote }}