{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banking.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
  annotations:
    # --- 12 LPA LOGIC: IAM ROLES FOR SERVICE ACCOUNTS (IRSA) ---
    # This allows the Pod to securely talk to AWS S3, RDS, or Secrets Manager
    # without using hardcoded credentials.
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Extra Audit Info
    eks.amazonaws.com/audience: "sts.amazonaws.com"
    eks.amazonaws.com/token-expiration: "86400"
automountServiceAccountToken: true
{{- end -}}