# --- SERVICE 1: THE PRODUCTION (ACTIVE) GATEWAY ---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking.fullname" . }}-active
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
  annotations:
    # Prometheus scrape for the LIVE version
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    # Argo Rollouts will dynamically inject a 'rollouts-pod-template-hash' 
    # here to point only to the "Stable" pods.
    app: {{ include "banking.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
# --- SERVICE 2: THE QA (PREVIEW) GATEWAY ---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking.fullname" . }}-preview
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    # Argo Rollouts will point this to the "New" version pods 
    # while they are being tested.
    app: {{ include "banking.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http