# # we create chart.yaml to define the metadata and versioning for our Helm chart, which is used to package and deploy our 
# banking platform microservices. This file specifies the chart name, version, description, and application version, 
# which helps in managing releases and dependencies when deploying to Kubernetes clusters using Helm.

apiVersion: v2      # it define the format/schema of the chart, v2 is the latest version that supports Helm 3 features and improvements
name: banking-platform   # Name of the Helm chart, used for identification and packaging
description: Production-grade Helm chart for Banking Microservices
type: application    # Type of chart (application means it deploys an application, as opposed to a library chart)
version: 1.0.0       # Version of the Helm chart itself, used for managing releases and dependencies
appVersion: "1.0.1"   # Version of the application being deployed, used for tracking the actual software version in the cluster