# Global settings
namespace: banking-prod
environment: prod
team: fintech
ownerEmail: "ruhondeb28@gmail.com"

# Replica settings
replicaCount: 1

# Image configuration
image:
  repository: 959589242185.dkr.ecr.us-east-1.amazonaws.com/banking-app
  tag: "v1.0.2"
  pullPolicy: IfNotPresent

# Service configuration
service:
  port: 80
  targetPort: 8080

# ConfigMap values
config:
  springProfile: prod
  logLevel: DEBUG
  dbHost: "bankapp-prod-db.c2hcaeaiydw4.us-east-1.rds.amazonaws.com"
  dbPort: "3306"
  dbName: "bankappdb"

# Secrets
secrets:
  awsSecretName: "banking-prod-db-secret"

# Service Account (IRSA)
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::959589242185:role/bankapp-prod-app-irsa-role

# Network Policy
network:
  databaseCidr: "10.0.0.0/16"

# HPA - disabled until Layer 9 (Prometheus installed)
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPU: 70
  targetMemory: 80

# Resources
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# ServiceMonitor - disabled until Layer 9 (Prometheus installed)
serviceMonitor:
  enabled: false
  path: "/actuator/prometheus"
  interval: "15s"

# Ingress - disabled until Layer 6 (Istio installed)
ingress:
  enabled: false
  host: "api.rohandevops.co.in"
  certificateArn: "arn:aws:acm:us-east-1:959589242185:certificate/59dfb445-8ebd-4c21-bcb8-097e66d45c1e"

# Istio - disabled until Layer 6
istio:
  enabled: false
  host: "api.rohandevops.co.in"

# VPA - disabled until Layer 14
vpa:
  enabled: true

# Observability
observability:
  otelCollectorEndpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
