apiVersion: v1
kind: Namespace

metadata:
  name: {{ required "namespace is required" .Values.namespace }}

  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

    env: {{ .Values.environment | default "prod" }}
    team: {{ .Values.team | default "fintech" }}

    managed-by: {{ .Release.Service }}

    istio-injection: enabled
    monitoring: prometheus

  annotations:
    description: Production environment for Banking Microservices
    owner: {{ .Values.ownerEmail }}