{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "banking.fullname" . }}
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "banking.labels" . | nindent 4 }}

  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/token-expiration: "86400"

automountServiceAccountToken: true
{{- end }}