apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: {{ include "banking.fullname" . }}-default-deny
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "banking.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      app: {{ include "banking.fullname" . }}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespace }}

        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system

        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring

      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort | default 8080 }}

  egress:
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system

      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Database
    - to:
        - ipBlock:
            cidr: {{ .Values.network.databaseCidr | default "10.0.0.0/16" }}

      ports:
        - protocol: TCP
          port: 3306

    # Observability stack
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring

      ports:
        - protocol: TCP
          port: 9090

        - protocol: TCP
          port: 3000

        - protocol: TCP
          port: 3100

        - protocol: TCP
          port: 4317

        - protocol: TCP
          port: 4318

        - protocol: TCP
          port: 9200