apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-banking-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp'
    targetRevision: HEAD
    path: k8s-manifests/argocd-infra
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/generation
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /metadata/resourceVersion
        - /metadata/generation
        - /spec/rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
