apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-banking-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rohandeb2/sspringboot-bankapp
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
      exclude: "{terraform/**,*.md,scripts/**,src/**,vars/**,.github/**,Dockerfile,docker-compose.yml,nginx.conf,pom.xml,mvnw,mvnw.cmd,.env,.gitignore,banking-app/**}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data
        - /spec/target
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec/rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
