# this file is created to define a PersistentVolumeClaim (PVC) for Jenkins, which allows Jenkins to have persistent storage for its data 
# (like job configurations, build history, plugins, etc.) even if the Jenkins pod restarts or gets rescheduled to another node. 
# The PVC will request 50Gi of storage and will be used by the Jenkins deployment to mount a persistent volume.

apiVersion: v1  # Kubernetes API version for core resources like Pod, PVC, Service, ConfigMap
kind: PersistentVolumeClaim  # Resource type: requests storage from the cluster
metadata:
  name: jenkins-pvc  # Name of this PVC; used by Jenkins to mount persistent storage
  namespace: jenkins  # The namespace where this PVC will exist; must match Jenkins namespace
spec:
  accessModes:
    - ReadWriteOnce  # pod can read/write this volume only from a single node means only one pod can use this PVC at a time, which is suitable for Jenkins master
  resources:
    requests:
      storage: 50Gi  # Amount of storage requested for Jenkins master (50 Gigabytes)