apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rohandeb2/sspringboot-bankapp'
    targetRevision: HEAD
    path: 'ci-cd'                          # was: k8s-manifests/cicd
    directory:
      include: '3_jenkins-all-manifests.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true