# service account is created because Jenkins agents need to assume an AWS IAM Role via IRSA to have permissions to interact
#  with AWS resources (like ECR, S3, etc.) during CI/CD pipelines.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent-sa
  namespace: jenkins
  annotations:
    # This is the "Magic Link" to your Terraform AWS Role
    eks.amazonaws.com/role-arn: arn:aws:iam::959589242185:role/jenkins-agent-irsa-role